resolver: lts-8.23

packages:
- '.'
- location:
    git: https://github.com/agrafix/Spock.git
    commit: 77333a2de5dea0dc8eba9432ab16864e93e5d70e
  subdirs:
    - Spock
    - Spock-core
    - reroute
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []
